"""bonus_phase5b_message_forwarding - Add message forwarding between threads and DMs

Revision ID: 5bd0d17e3bac
Revises: cf7a6a63690c
Create Date: 2025-11-11 14:19:12.778598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd0d17e3bac'
down_revision: Union[str, Sequence[str], None] = 'cf7a6a63690c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
