"""phase4_calendar_001 - Complete calendar system with sharing and Google sync

Revision ID: d8d046bdf68c
Revises: phase3_advanced_001
Create Date: 2025-11-11 13:49:57.452281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8d046bdf68c'
down_revision: Union[str, Sequence[str], None] = 'phase3_advanced_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_calendar_sync',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('google_access_token', sa.Text(), nullable=False),
    sa.Column('google_refresh_token', sa.Text(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('user_calendar_settings')
    op.drop_index(op.f('ix_admin_actions_action_type'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_created_at'), table_name='admin_actions')
    op.add_column('calendar_events', sa.Column('calendar_id', sa.UUID(), nullable=True))
    op.add_column('calendar_events', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('calendar_events', sa.Column('recurrence', sa.String(length=50), nullable=True))
    op.add_column('calendar_events', sa.Column('recurrence_end_date', sa.DateTime(), nullable=True))
    op.add_column('calendar_events', sa.Column('metadata_payload', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('calendar_events_user_id_fkey'), 'calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_events', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'calendar_events', 'calendars', ['calendar_id'], ['id'])
    op.drop_column('calendar_events', 'user_id')
    op.drop_index(op.f('ix_channel_roles_channel_id'), table_name='channel_roles')
    op.drop_index(op.f('ix_channel_roles_user_id'), table_name='channel_roles')
    op.drop_index(op.f('ix_device_sessions_is_active'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_user_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_flagged_content_created_at'), table_name='flagged_content')
    op.drop_index(op.f('ix_flagged_content_message_id'), table_name='flagged_content')
    op.drop_index(op.f('ix_flagged_content_status'), table_name='flagged_content')
    op.drop_index(op.f('ix_message_encryption_message_id'), table_name='message_encryption')
    op.add_column('messages', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_id'], ['id'])
    op.alter_column('search_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_search_index_indexed_id'), table_name='search_index')
    op.drop_index(op.f('ix_search_index_indexed_type'), table_name='search_index')
    op.drop_index(op.f('ix_security_audit_log_created_at'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_event_type'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_user_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_two_factor_auth_user_id'), table_name='two_factor_auth')
    op.add_column('user_activity', sa.Column('metadata_payload', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_user_activity_action'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_created_at'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_column('user_activity', 'metadata')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_suspensions_is_active'), table_name='user_suspensions')
    op.drop_index(op.f('ix_user_suspensions_user_id'), table_name='user_suspensions')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_column('users', 'status')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.create_index(op.f('ix_user_suspensions_user_id'), 'user_suspensions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_suspensions_is_active'), 'user_suspensions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.add_column('user_activity', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_created_at'), 'user_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_action'), 'user_activity', ['action'], unique=False)
    op.drop_column('user_activity', 'metadata_payload')
    op.create_index(op.f('ix_two_factor_auth_user_id'), 'two_factor_auth', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_user_id'), 'security_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_event_type'), 'security_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_log_created_at'), 'security_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_index_indexed_type'), 'search_index', ['indexed_type'], unique=False)
    op.create_index(op.f('ix_search_index_indexed_id'), 'search_index', ['indexed_id'], unique=False)
    op.alter_column('search_index', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_column('messages', 'parent_id')
    op.create_index(op.f('ix_message_encryption_message_id'), 'message_encryption', ['message_id'], unique=False)
    op.create_index(op.f('ix_flagged_content_status'), 'flagged_content', ['status'], unique=False)
    op.create_index(op.f('ix_flagged_content_message_id'), 'flagged_content', ['message_id'], unique=False)
    op.create_index(op.f('ix_flagged_content_created_at'), 'flagged_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_user_id'), 'device_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_sessions_is_active'), 'device_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_channel_roles_user_id'), 'channel_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_roles_channel_id'), 'channel_roles', ['channel_id'], unique=False)
    op.add_column('calendar_events', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.create_foreign_key(op.f('calendar_events_user_id_fkey'), 'calendar_events', 'users', ['user_id'], ['id'])
    op.drop_column('calendar_events', 'metadata_payload')
    op.drop_column('calendar_events', 'recurrence_end_date')
    op.drop_column('calendar_events', 'recurrence')
    op.drop_column('calendar_events', 'created_by')
    op.drop_column('calendar_events', 'calendar_id')
    op.create_index(op.f('ix_admin_actions_created_at'), 'admin_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_action_type'), 'admin_actions', ['action_type'], unique=False)
    op.create_table('user_calendar_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('google_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_calendar_settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_calendar_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_calendar_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('google_calendar_sync')
    op.drop_table('calendar_subscriptions')
    op.drop_table('calendar_members')
    op.drop_table('calendars')
    # ### end Alembic commands ###
